### ISSUE TITLE
How I can send a param in the command

### ISSUE THREAD

**Issue by VCGDEV** [BelirafoN/asterisk-ami-client#4]
Hi I using the ami-client and I have an ask:
How I can send a param in the command for instance, I want to send the command 'QueueStatus 9494', where the 9494 is the queue, this is my code
`
client.action({
           action: 'Command',
           actionID: '123',
           command : 'QueueStatus',
       },false);
`
Regards

**Comment by serfreeman1337** [comment]
"[Command](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Command)" action is using for sending CLI commands (asterisk -rx "").
Read asterisk docs.

If you want to get queue status via cli:
```
client.action({action: 'Command', Command : 'queue show 9494'}, false);
```

If you want to get queue status via [QueueStatus](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_QueueStatus) action:
https://github.com/BelirafoN/asterisk-ami-client/issues/2
